"""Moved to back populate

Revision ID: 1cd5b6d30e60
Revises: f6d9eecbe0cf
Create Date: 2025-09-16 05:04:16.181692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd5b6d30e60'
down_revision: Union[str, Sequence[str], None] = 'f6d9eecbe0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
